language: node_js
node_js:
  - "0.8"
# before_install: npm install -g grunt-cli
before_install:
  # - npm install -g npm
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
install: npm install
before_script:
  - grunt staging
